app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$uploadFile(inFile = "ct_min_data.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(`col.response` = "ct_val")
app$setInputs(`col.inc` = "Catorhintha schaffneri_APM")
app$snapshot()
app$setInputs(setseed = "2")
app$setInputs(iter = 100)
app$setInputs(simulate = "click")
app$setInputs(shinyalert = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(colour_exp = "black")
app$setInputs(plot = "click")
app$snapshot()
app$setInputs(`col.inc` = c("Catorhintha schaffneri_APM", "Catorhintha schaffneri_NPM"))
app$setInputs(simulate = "click")
app$setInputs(shinyalert = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(point_shape = "18")
app$setInputs(legend = "right")
app$setInputs(plot = "click")
app$setInputs(plot = "click")
app$setInputs(skews = "0, 10")
app$setInputs(tte_colrs = "black")
app$setInputs(tte_colrs = c("black", "forestgreen"))
app$setInputs(pop_n = 5)
app$setInputs(plot_tte = "click")
app$snapshot()
