app <- ShinyDriver$new("../../", seed = 123)
app$snapshotInit("mytest")

app$uploadFile(inFile = "ct_min_data.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(`col.response` = "ct_val")
app$setInputs(`col.inc` = "Eccritotarsus catarinensis_ETG16_Summer")
app$snapshot()
app$setInputs(setseed = "2")
app$setInputs(iter = 100)
app$setInputs(simulate = "click")
app$setInputs(shinyalert = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(colour_extrap = "seagreen")
app$setInputs(colour_exp = "coral1")
app$setInputs(alpha = 0.28)
app$setInputs(plot = "click")
app$setInputs(`col.inc` = c("Eccritotarsus catarinensis_ETG16_Summer", "Eccritotarsus catarinensis_ETG16_Winter"))
app$setInputs(simulate = "click")
app$setInputs(shinyalert = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(point_shape = "4")
app$setInputs(point_size = 3)
app$setInputs(legend = "bottom")
app$setInputs(plot = "click")
app$snapshot()
app$setInputs(skews = "0, 10")
app$setInputs(`col.inc.tte` = "Eccritotarsus catarinensis_ETG16_Summer")
app$setInputs(tte_colrs = "orange")
app$setInputs(tte_colrs = c("orange", "forestgreen"))
app$setInputs(pop_n = 5)
app$setInputs(plot_tte = "click")
app$snapshot()
