app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$uploadFile(inFile = "ct_min_data.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(`col.response` = "ct_val")
app$setInputs(`col.inc` = "Catorhintha schaffneri_APM")
app$snapshot()
app$setInputs(setseed = "2")
app$setInputs(iter = 100)
app$setInputs(simulate = "click")
# Input 'shinyalert' was set, but doesn't have an input binding.
app$setInputs(plot = "click")
app$setInputs(plot = "click")
app$setInputs(colour_exp = "black")
app$setInputs(plot = "click")
app$setInputs(`col.inc` = character(0))
app$setInputs(`col.inc` = "Catorhintha schaffneri_APM")
app$setInputs(`col.inc` = c("Catorhintha schaffneri_APM", "Catorhintha schaffneri_NPM"))
app$setInputs(simulate = "click")
# Input 'shinyalert' was set, but doesn't have an input binding.
app$setInputs(point_shape = "4")
app$setInputs(plot = "click")
app$setInputs(legend = "none")
app$setInputs(plot = "click")
app$setInputs(skews = "0, 10")
app$setInputs(tte_colrs = "orange")
app$setInputs(tte_colrs = c("orange", "forestgreen"))
app$setInputs(pop_n = 5)
app$setInputs(plot_tte = "click")
app$snapshot()
