library(shinytest2)

test_that("{shinytest2} recording: tests", {
  app <- AppDriver$new(name = "tests", seed = 123, height = 618, width = 847)
  app$upload_file(inFile = "ct_min_data.csv")
  app$set_inputs(col.response = "ct_val")
  app$set_inputs(col.inc = "Catorhintha schaffneri_APM")
  app$expect_values()
  app$set_inputs(setseed = "2")
  app$set_inputs(iter = 1)
  app$set_inputs(iter = 10)
  app$set_inputs(iter = 100)
  app$click("simulate")
  app$set_inputs(shinyalert = TRUE, allow_no_input_binding_ = TRUE, priority_ = "event")
  app$set_inputs(colour_exp = "black")
  app$set_inputs(alpha = 0.25)
  app$click("plot")
  app$set_inputs(col.inc = c("Catorhintha schaffneri_APM", "Catorhintha schaffneri_NPM"))
  app$click("simulate")
  app$set_inputs(shinyalert = TRUE, allow_no_input_binding_ = TRUE, priority_ = "event")
  app$expect_values()
  app$set_inputs(legend = "left")
  app$set_inputs(line_width = 1.35)
  app$set_inputs(point_shape = "4")
  app$expect_values()
  app$click("plot")
  app$set_inputs(skews = "0, 10")
  app$set_inputs(tte_colrs = "blue")
  app$set_inputs(tte_colrs = c("blue", "lightpink"))
  app$set_inputs(pop_n = 5)
  app$expect_values()
  app$click("plot_tte")
})
